version: '3.8'

services:
  s_apigateway:
    container_name: apigateway
    image: apigateway_image
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    networks:
      - net_api
      - int_net_api
    ports:
      - 9002:9002

  s_contact_api:
    container_name: contact_api
    image: contactapi_image
    build:
      context: .
      dockerfile: Services/Contact.API/Contact.API/Dockerfile
    networks:
      - int_net_api
    ports:
      - 9003:9003

  s_res_api:
    container_name: res_api
    image: resapi_image
    build:
      context: .
      dockerfile: Services/Reservation.API/Reservation.API/Dockerfile
    networks:
      - int_net_api
    ports:
      - 9004:9004

networks:
  int_net_api:
    driver: overlay
    internal: true
    attachable: true
  net_api:
    driver: bridge